<pre>
    INDEX

    COLOCAR AQUI RESUMO DO QUE PRECISA SER FEITO
    - ULTIMA VEZ QUE EXECUTOU O FETCHER
    - QUANTIDADES DE NOTICIAS QUE PRECISAM SER CLASSIFICADAS
        - LISTA HIERARQUICA
            - GERAL
            - POR INSTITUTI
            - POR BROADCASTER
</pre>